// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

type DeviceServiceClient interface {
	GetDevice(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceResponse, error)
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*DeviceResponse, error)
	StreamState(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (DeviceService_StreamStateClient, error)
	RegisterDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*DeviceResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) GetDevice(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceResponse, error) {
	out := new(DeviceResponse)
	err := c.cc.Invoke(ctx, "/gohome.DeviceService/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*DeviceResponse, error) {
	out := new(DeviceResponse)
	err := c.cc.Invoke(ctx, "/gohome.DeviceService/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) StreamState(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (DeviceService_StreamStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &DeviceService_ServiceDesc.Streams[0], "/gohome.DeviceService/StreamState", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceServiceStreamStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceService_StreamStateClient interface {
	Recv() (*DeviceState, error)
	grpc.ClientStream
}

type deviceServiceStreamStateClient struct {
	grpc.ClientStream
}

func (x *deviceServiceStreamStateClient) Recv() (*DeviceState, error) {
	m := new(DeviceState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceServiceClient) RegisterDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*DeviceResponse, error) {
	out := new(DeviceResponse)
	err := c.cc.Invoke(ctx, "/gohome.DeviceService/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DeviceServiceServer interface {
	GetDevice(context.Context, *DeviceRequest) (*DeviceResponse, error)
	SetState(context.Context, *SetStateRequest) (*DeviceResponse, error)
	StreamState(*DeviceRequest, DeviceService_StreamStateServer) error
	RegisterDevice(context.Context, *RegisterRequest) (*DeviceResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) GetDevice(context.Context, *DeviceRequest) (*DeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}

func (UnimplementedDeviceServiceServer) SetState(context.Context, *SetStateRequest) (*DeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}

func (UnimplementedDeviceServiceServer) StreamState(*DeviceRequest, DeviceService_StreamStateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamState not implemented")
}

func (UnimplementedDeviceServiceServer) RegisterDevice(context.Context, *RegisterRequest) (*DeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}

func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}

type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gohome.DeviceService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDevice(ctx, req.(*DeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gohome.DeviceService/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeviceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceServiceServer).StreamState(m, &deviceServiceStreamStateServer{stream})
}

type DeviceService_StreamStateServer interface {
	Send(*DeviceState) error
	grpc.ServerStream
}

type deviceServiceStreamStateServer struct {
	grpc.ServerStream
}

func (x *deviceServiceStreamStateServer) Send(m *DeviceState) error {
	return x.ServerStream.SendMsg(m)
}

func _DeviceService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gohome.DeviceService/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gohome.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevice",
			Handler:    _DeviceService_GetDevice_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _DeviceService_SetState_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceService_RegisterDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _DeviceService_StreamState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/device.proto",
}
