// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/device.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
const _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)

type DeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceId      string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceId      string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Room          string `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type SetStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceId      string  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IsOn          bool    `protobuf:"varint,2,opt,name=is_on,json=isOn,proto3" json:"is_on,omitempty"`
	Value         float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *SetStateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetStateRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *SetStateRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceId      string  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Room          string  `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	IsOn          bool    `protobuf:"varint,5,opt,name=is_on,json=isOn,proto3" json:"is_on,omitempty"`
	Value         float64 `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     int64   `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *DeviceResponse) Reset() {
	*x = DeviceResponse{}
}

func (x *DeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResponse) ProtoMessage() {}

func (x *DeviceResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DeviceResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeviceResponse) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *DeviceResponse) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *DeviceResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DeviceResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DeviceState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceId      string  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IsOn          bool    `protobuf:"varint,2,opt,name=is_on,json=isOn,proto3" json:"is_on,omitempty"`
	Value         float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DeviceState) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DeviceState) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceState) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

func (x *DeviceState) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DeviceState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_device_proto protoreflect.FileDescriptor
var file_proto_device_proto_rawDesc = []byte{}
var file_proto_device_proto_rawDescOnce sync.Once
var file_proto_device_proto_rawDescData = file_proto_device_proto_rawDesc
